make is new userの作成
3I-shikosai32/shikosai32-front pull request #122
Opened 2022-09-24 09:12 UTC by ituki0426

2022-09-24 13:36 UTC, dino3616 requested changes

2022-09-24 13:36 UTC, dino3616 commented on src/features/auth/is-new-user/components/Loading.tsx
> +import type { FC } from 'react';
フォーマットしてくださーい。
「huskyを入れろ！！」というのはﾕﾙｼﾃ...ﾕﾙｼﾃ...。
私のPCなんかhusky実行できないの...。

2022-09-24 13:36 UTC, dino3616 commented on src/features/auth/is-new-user/index.tsx
> +  const { data, fetching } = useFindUserBio({ uid: user.uid });
正直返却されるオブジェクトは何かしらのプロパティが一つだけあればいいので、`id`だけをレスポンスしてもらうためのGraphQL Queryを新しく作ってください。
多分そっちの方がコンマ単位で高速になります。

2022-09-24 13:36 UTC, dino3616 commented on src/features/auth/is-new-user/components/Loading.tsx
> +import type { FC } from 'react';
あと`Loading`コンポーネントは共有できるべきなので、`@/components`に設置して、StoryBookを作成してください。
また、`Loading`はデザインがまだ未着手なので、仮の実装で大丈夫です。

2022-09-25 21:55 UTC, dino3616 requested changes

2022-09-25 21:55 UTC, dino3616 commented on src/libs/graphql/documents/query/FindeUserNew.gql
> +query FindUserNew($id: String!) {
分からないこともないけどちょっと名前が分かりにくいので(日本語ガバ)、`DetectNewUser`とかにしましょう。

2022-10-02 06:54 UTC, ituki0426 commented on src/libs/graphql/documents/query/FindeUserNew.gql
> +query FindUserNew($id: String!) {
https://github.com/3I-shikosai32/shikosai32-front/pull/122/commits/401d51ac390731ae2e34932a224e7e9bf60bcca9

2022-10-02 06:55 UTC, ituki0426 commented on src/features/auth/is-new-user/components/Loading.tsx
> +import type { FC } from 'react';
https://github.com/3I-shikosai32/shikosai32-front/commit/8fe8ff0686092c6e247f0089db993837a770083d

2022-10-02 06:59 UTC, ituki0426 commented on src/features/auth/is-new-user/index.tsx
> +  const { data, fetching } = useFindUserBio({ uid: user.uid });
https://github.com/3I-shikosai32/shikosai32-front/blob/feat/117-make_isNewUser/src/libs/graphql/documents/query/DetectNewUser.gql

2022-10-03 05:13 UTC, dino3616 requested changes
もう少しだけRC対応願います💪

2022-10-03 05:13 UTC, dino3616 commented on src/libs/graphql/handlers/query/DetectNewUser.ts
> +  const [userNew] = useDetectNewUserQuery({ variables: { id: uid || '' }, pause: !uid, requestPolicy: 'cache-and-network' });
`userNew`というよりはシンプルに`result`でいいと思います。
加えて`uid || ''`も気になるので、まとめて以下のような感じでいいかなと思います。

```ts
const [result] = useDetectNewUserQuery({ variables: uid ? { id: uid } : undefined, pause: !uid, requestPolicy: 'cache-and-network' });
```

2022-10-03 05:18 UTC, dino3616 commented
あれ？そういえば`pages`にページコンポーネントを作成した？
まだであれば対応願います🙏

2022-10-10 14:56 UTC, ituki0426 commented on src/features/auth/is-new-user/index.tsx
> +  if (!user) {
https://github.com/3I-shikosai32/shikosai32-front/pull/122/commits/6da596d58788bb42182d1d2d05388bb8ba93f54e

2022-10-10 14:56 UTC, ituki0426 commented on src/features/auth/is-new-user/index.tsx
> +const FindUserById: FC<{ user: User }> = ({ user }) => {
https://github.com/3I-shikosai32/shikosai32-front/pull/122/commits/6da596d58788bb42182d1d2d05388bb8ba93f54e

2022-10-10 14:57 UTC, ituki0426 commented on src/libs/graphql/handlers/query/DetectNewUser.ts
> +export const useDetectNewUser = ({ uid }: UseFindUserNewProps) => {
https://github.com/3I-shikosai32/shikosai32-front/pull/122/commits/b3aaafea0d3e3560271245127953d29b7578065a

2022-10-10 14:57 UTC, ituki0426 commented on src/libs/graphql/handlers/query/DetectNewUser.ts
> +  const [userNew] = useDetectNewUserQuery({ variables: { id: uid || '' }, pause: !uid, requestPolicy: 'cache-and-network' });
https://github.com/3I-shikosai32/shikosai32-front/pull/122/commits/b3aaafea0d3e3560271245127953d29b7578065a

2022-10-13 05:11 UTC, closed without merging