Feat/123 make new user
3I-shikosai32/shikosai32-front pull request #135
Opened 2022-09-28 11:35 UTC by ituki0426

# 実装済み機能
- フォーム欄
- キャラクター選択(要修正箇所1つ)
- ページ上部（要修正箇所多数）
# 未実施の機能
- reateUserMutationの実行

2022-09-29 04:48 UTC, dino3616 requested changes
全体的にformat忘れが目立ちます。
Draftとはいえ、「formatを実行」のようなcommitが乱立するとgitを使っている意味が薄れるので、VScodeで「ファイル保存時にlinter/formatterを実行する」みたいな設定をすることをオススメします。

あとファイルの命名規則は統一してください。

2022-09-29 04:48 UTC, dino3616 commented on src/features/new-user/components/Top.tsx
> +      <div className='font-branding text-4xl'>Welcom!</div>
多分フォント違います。

2022-09-29 04:48 UTC, dino3616 commented on src/features/new-user/components/Top.tsx
> +        <Image src="/logos/header.png" alt="Logo" width={150} height={150} />
画像が違います。

2022-09-29 04:48 UTC, dino3616 commented on src/features/new-user/components/Top.tsx
> +  <div>
このリポジトリではスタイル無しの"コレ"は`React/Fragment`で統一しているので、`</>`でラップしてください。

2022-09-29 04:48 UTC, dino3616 commented on src/libs/graphql/documents/mutation/createUser.gql
> +}
最後の改行が足りないです。
フォーマットしてください。

2022-09-29 04:48 UTC, dino3616 commented on src/pages/auth/new-user.tsx
> +const NewUserpage: NextPage = () => <NewUser />;
コンポーネント名はUpperCamelCaseで記述してください。

2022-09-29 04:48 UTC, dino3616 commented on src/pages/auth/new-user.tsx
> +const NewUserpage: NextPage = () => <NewUser />;
あと`Layout`でラップしてください。

2022-09-29 04:48 UTC, dino3616 commented on src/features/new-user/components/form.tsx
> +          id="floating_password"
`id`属性が下のと被ってます。
それはそうとここに`id`属性って本当にいるんでしたっけ...？

2022-09-29 04:48 UTC, dino3616 commented on src/features/new-user/components/character.tsx
> +  boxMergin: string;
これだとtailwindの補完が効かないのでマズイです。
多分`m-3`でしか使用していないと思うので、`Props`にあるべきものではないのかなと思います。

2022-09-29 04:48 UTC, dino3616 commented on src/features/new-user/components/Submit.tsx
> +      <Button type="submit" className='bg-primary'><ButtonIcon><AiOutlineSend /></ButtonIcon>Sign Up</Button>
デザインはグラデーションなので、実装もグラデーションにしてください。
`tailwind.config`に該当する設定がなければfigmaからカラーコードをコピーしてきてください。

2022-09-29 04:48 UTC, dino3616 commented on src/features/new-user/components/Top.tsx
> +      <div>
この`<div>`は必要ですか...？
時間の都合上GitHub上でしかレビューしていないので、消すことで機能を損なうようであれば、このレビューは気にしないでください。

2022-09-29 04:48 UTC, dino3616 commented on src/features/new-user/components/character.tsx
> +  checkboxSize: number;
`checkboxSize`と`imageSize`はPropsというよりは、このコンポーネント内でハードコーディングするだけでいい変数かなと思います。
...多分...(？

2022-09-29 04:48 UTC, dino3616 commented on src/features/new-user/components/character.tsx
> +  const icons = ['cat', 'fox', 'goku', 'pudding', 'reaper', 'tree'];
`gql:gen`で生成された`Character`を配列として使った方がいいと思います。

2022-09-29 04:48 UTC, dino3616 commented on src/features/new-user/components/character.tsx
> +  const icons = ['cat', 'fox', 'goku', 'pudding', 'reaper', 'tree'];
`icons`というよりは...`characters`...(？

2022-09-29 04:48 UTC, dino3616 commented on src/features/new-user/components/character.tsx
> +      {icons.map((item) => (
`item`はこのリポジトリだと`Item`ドメインを連想させるので、これは元配列の単数形にしましょう。

2022-09-29 04:48 UTC, dino3616 commented on src/features/new-user/hooks/useForm.ts
> +const useForm = (props: Props) => {
現段階ではcustom hookにする必要ないような気がします。
まだ完全なレビューとは言えないので、Draftを解除したときに最終的な判断をします。

2022-10-01 13:34 UTC, ituki0426 commented on src/features/new-user/new-user.story.ts
> +};
# 質問

![image](https://user-images.githubusercontent.com/82156802/193412035-39260ef1-02ca-476f-b225-20ad757fc8a1.png)

このエラーの解決法帆を教えてください

2022-10-01 13:45 UTC, ituki0426 commented on src/features/new-user/new-user.story.ts
> +};
# 質問
![image](https://user-images.githubusercontent.com/82156802/193412488-c2dedcc7-b0c7-4252-a74f-8bd3daffca9c.png)
このエラーの解決方法をお教えてください

2022-10-01 13:55 UTC, ReoHakase commented on src/features/new-user/new-user.story.ts
> +};
このストーリーで描画しようとしてるコンポーネントが、Recoilの`atom`や`selector`などから値を受け取るコンポーネントに依存しているみたいですね👀
Recoilのストアの値を使うときは、使用元のコンポーネントが必ず`<RecoilRoot>`の子孫要素になっていないといけないので、`このコンポーネントは<RecoilRoot>の中で使用する必要があります`というエラーがでます。
解決方法のうちのひとつとして、ストーリー全体を囲うラッパーを指定できる`decorators`を使って`<RecoilRoot>`の中にいれてあげると思います。
```tsx
// 例 Header.story.tsx
const meta: ComponentMeta<typeof Header> = {
  component: Header,
  parameters: {
    layout: 'fullscreen',
  },
  decorators: [(story) => <RecoilRoot>{story()}</RecoilRoot>],
  argTypes: {
    className: {
      description: '`position: sticky`やサイズの変更のために指定できます。',
      control: { type: 'text' },
    },
  },
};
```

2022-10-01 14:31 UTC, ituki0426 commented on src/features/new-user/new-user.story.ts
> +};
![image](https://user-images.githubusercontent.com/82156802/193414308-c1418392-9c92-45fb-a75d-dffdd71a60f8.png)

このようなエラーの場合はどうすれば良いですか？

コード
```tsx
// eslint-disable-next-line import/no-extraneous-dependencies
import type { ComponentStoryObj, ComponentMeta } from '@storybook/react';
import NewUser from './index';
import { RecoilRoot } from 'recoil';

type Story = ComponentStoryObj<typeof NewUser>;

const meta: ComponentMeta<typeof NewUser> = {
  component: NewUser,
  parameters:{},
  decorators: [(story) => <RecoilRoot>{story()}</RecoilRoot>],
};

export default meta;

export const Default: Story = {};
```

2022-10-01 14:35 UTC, ReoHakase commented on src/features/new-user/new-user.story.ts
> +};
たぶんファイルの拡張子が`.tsx`ではなく`.ts`になっているせいでJSXが扱えていませんね...
ファイル名を`new-user.story.tsx`に変えてみてください！

2022-10-01 14:47 UTC, ituki0426 commented on src/features/new-user/new-user.story.ts
> +};
ありがとうございます

2022-10-01 16:38 UTC, dino3616 commented
conversationを解決したら、それを解決したcommitのurlを該当する箇所でリプしてください。
問題ないようであればresolve conversationとしてスレッドを閉じます。

2022-10-02 02:29 UTC, ituki0426 commented on src/features/new-user/components/form.tsx
> +          id="floating_password"
https://github.com/3I-shikosai32/shikosai32-front/pull/135/commits/f29e5d19be872c1e1b98fa032a6cb3138e365587

2022-10-02 02:32 UTC, ituki0426 commented on src/features/new-user/components/Top.tsx
> +        <Image src="/logos/header.png" alt="Logo" width={150} height={150} />
https://github.com/3I-shikosai32/shikosai32-front/pull/135/commits/8c4591cd5b952f3f8987af420905e749d841256d

2022-10-02 02:33 UTC, ituki0426 commented on src/pages/auth/new-user.tsx
> +const NewUserpage: NextPage = () => <NewUser />;
https://github.com/3I-shikosai32/shikosai32-front/pull/135/commits/0a4fb8f31c2096d7c5e54dfbe087b161989300bd

2022-10-02 02:38 UTC, ituki0426 commented on src/libs/graphql/documents/mutation/createUser.gql
> +}
https://github.com/3I-shikosai32/shikosai32-front/pull/135/commits/c0dbbf27d3b7943341166d6bb86b6fb9d141f718

2022-10-02 02:49 UTC, ituki0426 commented on src/features/new-user/components/character.tsx
> +  const icons = ['cat', 'fox', 'goku', 'pudding', 'reaper', 'tree'];
https://github.com/3I-shikosai32/shikosai32-front/commit/9890690ad75d9dd845d1d2e9d2acf5d38b64e25a

2022-10-02 02:49 UTC, ituki0426 commented on src/features/new-user/components/character.tsx
> +  checkboxSize: number;
https://github.com/3I-shikosai32/shikosai32-front/commit/9890690ad75d9dd845d1d2e9d2acf5d38b64e25a

2022-10-02 02:51 UTC, ituki0426 commented on src/features/new-user/components/character.tsx
> +      {icons.map((item) => (
https://github.com/3I-shikosai32/shikosai32-front/commit/9890690ad75d9dd845d1d2e9d2acf5d38b64e25a

2022-10-02 02:54 UTC, ituki0426 commented on src/features/new-user/components/Top.tsx
> +      <div>
https://github.com/3I-shikosai32/shikosai32-front/pull/135/commits/49dde10dcd7f9e530bf6a9c4ae8aca60fd5e2f84

2022-10-02 02:54 UTC, ituki0426 commented on src/features/new-user/components/Top.tsx
> +  <div>
https://github.com/3I-shikosai32/shikosai32-front/pull/135/commits/49dde10dcd7f9e530bf6a9c4ae8aca60fd5e2f84

2022-10-02 10:29 UTC, ituki0426 commented on src/features/new-user/components/character.tsx
> +  const icons = ['cat', 'fox', 'goku', 'pudding', 'reaper', 'tree'];
https://github.com/3I-shikosai32/shikosai32-front/pull/135/commits/b8d6b5a585c1f2d239cf91ec79fd7e7230365f62

2022-10-03 08:06 UTC, dino3616 commented
Issuesを紐づけてくれ

2022-10-03 08:11 UTC, dino3616 requested changes
![image](https://user-images.githubusercontent.com/85730998/193529847-975315e8-1cb1-4a55-845a-411502410411.png)

- ロゴ画像がヘッダーの上に来る
- キャラ画像がロードされない
- インプットの色が違う

これだけ直してください。
ロジックに関しては、リファクタリングした方がよさそうなところはありましたが`react-hook-form`を使う以外に簡潔で具体的な解決案が思い浮かばなかったので、一旦これで通します。

2022-10-08 13:18 UTC, ituki0426 commented
https://github.com/3I-shikosai32/shikosai32-front/pull/135/commits/11b06c6e69d7d0073d205a90d4b5fd00442878fe

2022-10-09 04:38 UTC, dino3616 requested changes

2022-10-09 04:38 UTC, dino3616 commented on src/features/new-user/components/character.tsx
> +          <Image src={`/characters/${character.toLowerCase}.svg`} width={110} height={110} alt="My icon" />
`toLowerCase`は多分関数なので実行してください。
めんどうですが、人間ミスはあるのでコミットする前に必ず手動テストをしましょう。

2022-10-09 04:39 UTC, dino3616 commented
> 修正の仕方がわからん

これはブランチをupdateすると修正されます。

2022-10-09 09:40 UTC, dino3616 requested changes
申し訳ないが、レスポンシブもうちょいがんばって

![image](https://user-images.githubusercontent.com/85730998/194749589-b20280d8-ef5c-4dc1-a0c4-a962aead5276.png)

2022-10-10 14:50 UTC, ituki0426 commented
# 質問

next/imageのImageの大きさをレスポンシブにする方法を教えてください

2022-10-11 01:18 UTC, ituki0426 commented
# 修正(レスポンシブ)

https://github.com/3I-shikosai32/shikosai32-front/pull/135/commits/96b1acecf0d9ff4f98f5bcfa66f9776e40b6a4fb

2022-10-11 20:55 UTC, dino3616 approved these changes

2022-10-11 20:56 UTC, merged