Fix/rearchitect
3I-shikosai32/shikosai32-front pull request #196
Opened 2022-10-08 16:09 UTC by ReoHakase

2022-10-09 09:28 UTC, dino3616 requested changes
## Summary

ちゃんとレビューはしますが、これが最善策ではないであろうことに留意してください。
また最悪の場合、諦めるという選択肢も用意しておいてください。
確かに綺麗なアーキテクチャを構築できれば、フロントエンド開発で容易にクソコードが生まれてしまう(もちろん私もそう)問題を解決できますが、多分現役のプログラマの方もやっている人は少数じゃないかと思います。
それくらい複雑なことなので、ぶっちゃけ明らかにぶっつけ本番でやることではなく、プロトタイプを作ってしっかり検証すべきことだと思います(そんなことしている暇はないので、できないのはしょうがないですが...)。

## Entity

`entity`...というよりは`model`？
個人的には、`entity`というとDBに関心を持つオブジェクトが想起されます。
(というかDDDにおける様々なアーキテクチャでこの`Entity`という言葉が全く異なる意味で多用されているので、前提としてこういうアーキテクチャを基にしてる的な情報がないと一瞬でLowContextに成り果てる...。~~なんとかしたいですよね(|)~~)

また、例えば`entity/User`を例にとると、ここでは複数のドメインが一つのファイルに定義されていますが、これは一つのファイルにつき一つのドメインにするべきだと思います。

==以下絶賛悩み中思考==
そして実装上、`react`が関数型プログラミングの味が強いので悩ましい所ですが、ドメインルールを作りたいとなったときのために、クラスとして記述するべきじゃないかなぁ...と思ったり...。
でもそうするならいっそ`FC`じゃなくて`extends Component`の方がいいのでは...？と思ったり...。
わがんね。

## Presentation

UIに関心を持つ部分としてそれ用のディレクトリが切られていないので、`src`にロジックとUIが混在しているのが気になります。
そしてこの問題は、`pages`と`features`を合体することで解決するんじゃないかと思います。
やったことないので分かりませんが、`Next.js`は`pages`にある`export default`された`NextPage`をページコンポーネントとして認識するはずで、`pages/**/*.tsx`に含まれる`FC`はどうでもいいはずです。
そのため、`pages`を`Persentation`層として運用するのがいっちゃんいいかなぁと思いました。

## UseCase

やっぱ`infra`にいる`urql`の関数を`UseCase`で直呼びしてるのは...うーーん...。
たとえば`UserRepository`みたいなクラス or 関数をまとめたオブジェクトを返す関数を作って、そこで`User`に関するfetch処理を書く...みたいなことをしたい。
そうすれば途中でRESTに変えますってなっても、Repositoryの実装を変える(理想的なのは`UserRepositoryREST`みたいなのを作って、それを依存に注入する)がいい希ガス...。

```tsx
export class UserRepositoryREST {
  constructor(private readonly http: HttpClient) {}

  fetchAll(offset?: number, limit?: number): Promise<Todo[]> {
    return this.http.get(url, params).then(/* 一覧データ */);
  }

  fetch(id: number): Promise<Todo> {
    return this.http.get(url, params).then(/* 詳細データ */);
  }

  create(todo: TodoCreateDto): Promise<Todo> {
    return this.http.post(url, body).then(/* 登録データ */);
  }

  update(id: number, todo: TodoUpdateDto): Promise<Todo> {
    return this.http.put(url, body).then(/* 更新データ */);
  }

  remove(id: number): Promise<number> {
    return this.http.delete(url).then(/* 削除されたデータのID */);
  }
}
```

## Directory

```
/* src */
- domain
  - model
  - service // わからん
- infra
- pages
  - common
  - layout
- repositoty
- use-case
```

正直`util`はクソコードの温床なのでこういった命名は極力したくないという理由で、あえて書いていません。

以下、各ディレクトリの責務について。

- domain/model
  - ドメインモデルを定義する場所。ドメインモデルをクラスとして書くべきなのか、それとも単なる型として書くべきなのかについては...、本当にわからん...。
  - `domain/service`がない場合は`model`でいいですね。
- domain/service
  - オニオンアーキテクチャにおけるドメインサービス層に従い、各層で記述されるオブジェクトのインターフェースを定義する場所。リアーキテクトをする目的がGraphQL Schemaを隠蔽したいってことだったので、依存性を逆転させる必要があるんじゃないかなと思った。
  - でもこれすると、実態をどうやって注入するんじゃいって問題に直面するので、私にはわからん。`react-magnetic-di`で解決できるんかな...？
- infra
  - 外部ライブラリやフレームワークの補助的な関数とかを定義する場所。
- pages
  - `FC`や`NextPage`を定義する場所。`Presentation`層そのもの。
  - `Presentational Component`と`Container Component`がいる場所。
- pages/common
  - `Button`とか`Card`とかがいる場所。
- pages/layout
  - `Layout`がいる場所。`layout`という一つの`feature`として考える。
- repository
  - fetch用の関数群を定義する場所。
- use-case
  - ドメインに対するユースケースを定義する場所。`repository`に依存し、`pages`の`Container Component`に依存される。

2022-10-09 11:44 UTC, ReoHakase commented
とりあえずの決定事項:
- `domain/service`はURQLからの変更は考えられないので、つくらない
- `repository`も同様の理由で作らない

2022-10-09 11:51 UTC, ReoHakase commented
- `utils/twmerge`は`src/presentation`以下に移す
- `characterDictionary`は`model`以下に移す

2022-10-09 12:06 UTC, ReoHakase commented
ファイル構造の命名規則
- 単数形で統一
- ケバブケース`kebeb-case`で統一
- ファイル名に対応した接尾詞をつける e.g. `MyComponent.component.ts` `user.model.ts`
---
参考: [https://angular.io/guide/styleguide](https://angular.io/guide/styleguide)

2022-10-09 12:40 UTC, dino3616 commented
## 補足

例えばコンポーネントの場合、Angular的には変数は`HogeComponent`でファイル名は`hoge.component.tsx`とするのが好ましいですが、reactにおいてコンポーネントはおおよそJSXの中でしか使わないため、変数名は`Hoge`でファイル名は`hoge.component.tsx`というように、変数に接尾辞は不要となります。
ただユースケースの場合、一目でこれはユースケースの変数だなと分かりたいので、変数名は`HogeUseCase`でファイル名は`hoge.use-case.tsx`というようにしてください。

2022-10-10 07:59 UTC, dino3616 requested changes
前回より断然見やすくなりましたね。
Greate Jobです💪

## Summary

- 技術駆動パッケージングになっているので、ドメイン駆動パッケージングにしたいなぁ...と思いつつ、まぁ今から変えるとなるとアサイニーの脳が破壊されそうなので、うーーーん...。自分からの回答はいつもの「アサイニーに任せる」でお願いするます。

## Model

stateにしか使われていない型定義もドメインモデルとしてあるのがちょっと気になります。
本来ドメインモデルというのは、アプリケーション全体で取り上げられる領域を抽象化したものであるべきです。
また、Data Transfer Objectがdomain modelのフォルダのルートに混在しているのも、ちょっち気になります。
とはいえ、今回の場合はそこまでちゃんとしたDDDではないということと、自分自身上に述べたことが正しいのかについて確証がないため、とりあえずおおまかな部分はこのままでもあｐｐろヴぇとします。
~~動くコードが正義です~~

以下、細かな修正依頼です。

- `Id`はドメインモデルではない気がする。普通に`string`でいい気がする。`ResourceURL`も同様。
- `character.model.ts`は`character`フォルダで囲ってください。

## Presentation

- `Container / Presenter`デザインパターンを導入するのであれば、旧featureディレクトリに価する場所には、以下のようなファイル群が必要です。
  - `.container`
  - `.presenter`
- `common`に`twmerge`があるのは...うーーーーん...。安直に考えると、`tailwind-merge`って`tailwind`のための技術で、`tailwind`って`CSS`のための技術で、`CSS`ってstyleのための技術なので、`twmerge`は`style`にあるのが適切なのかなぁと思ったり...。
- そうすると、`common/component`は`common`でいいなぁ...。
- それはそうと、`style`は`presentation`にあるべきです。
- `layout`...。ちょっと考えましたが、`pages`に`__layout__`的な感じで作るのはどうでしょう...？
- `game`とか`gift`とかは`module`か`component`的なフォルダで囲みましょう。...いや命名的になんかしっくりこないな...。`unique`...？？？`page`...？？？
- 現時点でまとめるとこうです。
```
- presentation
  - common
    - button
  - page(?)
    - index
  - style
    - global.scss
    - twmerge
```

## State

- `recoil-key`は`@/constant`に入れるべきです。
- `auth-state`は`auth`フォルダで囲んじゃってください。

## Others

- GraphQL Queryのファイル名が規約に則っていない。
- 不要な.gitkeepファイルがある。(正直全部いらない)

2022-10-10 11:59 UTC, dino3616 commented
> 対応しました！

good job👍

> 個人的にはstyle/以下は.scssファイル以外のものを置きたくないから今のcommon/以下でいい気もします

すごくよく分かる。
でも`common`って一般とか凡庸的な意味合いなので、`twmerge`がそこにあるのは気持ち悪い...。
じゃぁこんなんでどう？

```
- style
  - scss
  - twmerge
```

2022-10-10 12:07 UTC, ReoHakase commented
> > 対応しました！
> 
> good job👍
> 
> > 個人的にはstyle/以下は.scssファイル以外のものを置きたくないから今のcommon/以下でいい気もします
> 
> すごくよく分かる。 でも`common`って一般とか凡庸的な意味合いなので、`twmerge`がそこにあるのは気持ち悪い...。 じゃぁこんなんでどう？
> 
> ```
> - style
>   - scss
>   - twmerge
> ```

```
style
- stylesheet
- twmerge
```

2022-10-10 12:13 UTC, dino3616 commented
それな。
あｐｐろヴぇ。

2022-10-10 13:03 UTC, ReoHakase commented
> - Container / Presenterデザインパターンを導入するのであれば、旧featureディレクトリに価する場所には、以下のようなファイル群が必要です。
.container
.presenter

対応しました

> - layout...。ちょっと考えましたが、pagesに__layout__的な感じで作るのはどうでしょう...？
gameとかgiftとかはmoduleかcomponent的なフォルダで囲みましょう。...いや命名的になんかしっくりこないな...。unique...？？？page...？？？

んーいい案が思いつかない... このままでもいい気がする

2022-10-10 23:58 UTC, dino3616 commented
イチャモンみたいなレビューになって申し訳ない...。
これらに対する自分の今の考えはこんな感じ。

- `layout`
  - `index`や`gift`に対して、`layout`の使われ方はちょい違う(どちらかというと`common`的な意味合いの方が強い)。
  - だったら`pages`に`__layout__`として入れたい(mustってわけでもない)。
- 機能component
  - `common`と同階層で`index`なり`gift`なりが散乱してるのは気持ち悪い...。
  - 現`common`を`atom`にして、`index`なり`gift`なりを`molecule`ってするのはどう...？

2022-10-11 20:45 UTC, dino3616 requested changes
Greatefull Job💪

多分最後のRCです。
`primitive/component`を単に`primitive`としてください。
従来の`feature`であれば`primitive/hook`とかもあり得ましたが、現行の構成だと`presentation`に`hook`を書くことはまずないと思います。

2022-10-12 15:22 UTC, ReoHakase commented
例えばの話だけど、もしこれから日付のフォーマット用のフックを共通化しようと思うと、
- 外部サービスに依存しない
- 現在時刻からみた差をもとめるから内部`state`をもつ = フックである必要がある
- 横断的に使う機能
だから、その置き場所は`src/presentation/primitive/hook`が妥当になると思うんだよね。

```tsx
import { formatDistance } from 'date-fns';
import ja from 'date-fns/locale/ja';
import { useCallback, useEffect, useState, useMemo } from 'react';

const useFormatDate = (date: Date) => {
  const [now, setNow] = useState(new Date());

  // 10秒ごとに現在時刻を更新する
  useEffect(() => {
    const interval = setInterval(() => {
      setNow(new Date());
    }, 10000);
    return () => {
      clearInterval(interval);
    };
  }, [now, setNow]);

  const result = useMemo(() => formatDistance(date, now, { locale: ja, includeSeconds: true }), [date, now]);
  return result;
};
```

ようするに、将来のために`primitive/component`は残しておいてもいい...と思うんだけどどうかな？

2022-10-12 15:32 UTC, dino3616 commented
うーん...hookってロジックじゃん？
ロジックがpresentationにあるのは変じゃね？

2022-10-12 15:52 UTC, ReoHakase commented
日付のフォーマットと今回はやらないローカライゼーションは、表示をわかりやすくするためのもので、なおかつ依存する先が現在時刻と使用言語のみに限られてるから、`src/presentation/primitive/hook`に置いて`.presenter.tsx`から参照できるようにしてもいいとは思うんだよね。
それを許すといちいち`.container.tsx`で見た目にしか影響しない日付のフォーマットをして`.presenter.tsx`にわたすってことをしなくて良くなるから、変では無いんじゃないかなぁ🤔
ただ、その場合`.presenter.tsx`が副作用をもってしまうから気持ち悪い...

2022-10-12 16:05 UTC, dino3616 commented
`useFormatDate`はドライバーに関する(ドライバーに依存する)操作だから`infra`に置けばいいんじゃないかなぁ...？
もしくは、ただ日付をフォーマットする(Dateを指定の文字列にするとか)をするだけの関数だったら、いっそのことutilを作ってしまうのもアリかも...。

2022-10-12 16:31 UTC, dino3616 commented
んー、確かに`.presenter`から直接`infra`に依存するのは気持ち悪いな。
いやでもやっぱり、`presentation`に直接ロジックがあるのも気持ち悪い...。
ロジックを組み合わせてる`.container`は別にいいんだけどね。
じゃぁこういうんはどう？

```
- common
  - constant
  - hook
```

いやまぁこれもこれでアンチパターンではあるんだけど...。

2022-10-12 16:39 UTC, dino3616 commented
(`infra`にdateの処理を置いて`.container`がdateに依存するという手もある)

2022-10-12 16:54 UTC, ReoHakase commented
> (`infra`にdateの処理を置いて`.container`がdateに依存するという手もある)

`date`の処理(今回の現在時刻を基準にした文字列に変換する e.g. `3分前`)は、副作用を持つから`.container.tsx`に置くべきかもしれないけど、
この`date`の処理は見た目にしか影響しないわけだし、提案通り`presentation/primitive/hook/date/format-date-in-distance.hook.ts`を`.presenter.tsx`から参照する設計でいい？

2022-10-12 17:00 UTC, dino3616 commented
んまぁー...いいと思うます👍

2022-10-12 18:10 UTC, dino3616 submitted a review, later dismissed
お疲れさまあｐｐろヴぇ。

2022-10-12 19:05 UTC, dino3616 approved these changes

2022-10-12 19:05 UTC, merged