景品交換ページ`/gifts`を作成した。
3I-shikosai32/shikosai32-front pull request #209
Opened 2022-10-14 16:22 UTC by ReoHakase

- close #13 

# 概要
## 実際のページの見た目
未ログイン状態です。
![image](https://user-images.githubusercontent.com/16751535/195894417-e6007047-7373-405b-be22-9654440544ac.png)

## `<GiftIndex>` (`gift-index.presenter.tsx`)
![image](https://user-images.githubusercontent.com/16751535/195893926-a66ba034-d4df-4a33-a3f8-b66f1c8bc93c.png)
![image](https://user-images.githubusercontent.com/16751535/195893950-c34d9a04-3e20-4a35-ba2b-c961482828fb.png)
![image](https://user-images.githubusercontent.com/16751535/195893979-6fea6c97-2a87-4923-b2f9-96e869597fe4.png)
![image](https://user-images.githubusercontent.com/16751535/195894003-d2357df2-297a-4511-adb1-0bc991604daa.png)
![image](https://user-images.githubusercontent.com/16751535/195894022-e6b5e526-44f8-4bd1-9bfc-19c5f92488e1.png)

2022-10-15 01:53 UTC, dino3616 requested changes

2022-10-15 01:53 UTC, dino3616 commented on src/presentation/relevant/gift/gift-index.presenter.tsx
> +  if (gifts.length < 1) {
仮に`-1`とかが返ってきたのを例外として検知できないと怖いので、

```suggestion
  if (gifts.length == 0) {
```

でいいんじゃないかと思います。

2022-10-15 01:53 UTC, dino3616 commented on src/presentation/relevant/gift/gift-index.presenter.tsx
> +            あなたも景品のために遊ぼう！
景品のために遊ぶ...わけではないのかなぁ...。
だとしたらこんな感じの方がいいかも。
(ソシャゲの悪質広告感が否めないけど)

```suggestion
            まだOZに参加してない？
            <br />
            今すぐ登録・ログインして、
            <br />
            アソビの頂点を目指そう！
```

2022-10-15 01:53 UTC, dino3616 commented on src/presentation/relevant/gift/gift-index.presenter.tsx
> +      {(!gifts || gifts === null || gifts.length < 1) && (
これも`length`は`0`で。

```suggestion
      {(!gifts || gifts === null || gifts.length == 0) && (
```

2022-10-15 01:56 UTC, dino3616 commented on src/infra/graphql/document/mutation/exchange-gift.gql
> +mutation ExchangeGift($userId: String!, $giftId: String!, $amount: Float!) {
あれーおっかしいなぁ...なんで`Float!`なんやろなぁ...。
って思ってサーバーのコード見直したらサーバーに問題がありました。
https://github.com/3I-shikosai32/shikosai32-server/issues/267 で解決します。

2022-10-15 06:51 UTC, ReoHakase commented on src/infra/graphql/document/mutation/exchange-gift.gql
> +mutation ExchangeGift($userId: String!, $giftId: String!, $amount: Float!) {
#267 を先程マージしたのでそれにあわせて修正しておきます！

2022-10-16 02:01 UTC, dino3616 approved these changes

2022-10-16 02:04 UTC, merged