feat: ✨ Toggleを作成
3I-shikosai32/shikosai32-front pull request #69
Opened 2022-09-10 10:12 UTC by ituki0426

## Support

Toggleを作成した
引数
 - color: 'bg-gray-500’のようにして指定する
 - size: 'small' , 'mid',  'large' から選択する

## Related Issues

- close #27

2022-09-10 11:14 UTC, ReoHakase requested changes

2022-09-10 11:14 UTC, ReoHakase commented on src/components/Toggle/index.tsx
> +export type ToggleProps = {
ここで定義されている型`ToggleProps`が実際に使われていないみたいです。`FC<>`に渡す`props`の型の指定をこれで済ませて、型も`export`するといろいろ再利用ができて楽なので良いと思います。

2022-09-10 11:14 UTC, ReoHakase commented on src/components/Toggle/index.tsx
> +            <input id="toggle" type="checkbox" onClick={onClick} className="peer sr-only" />
引数を受け取らない`onClick`イベントハンドラのみしか指定できないので、私の知る範囲だと外部からトグルボタンの入力値をReactの`state`で管理できない...ように思えます。
自分はいつも`value`と`onChange`を受け取るようにしています。その場合の型指定は、`ComponentPropsWithoutRef`を使用するとHTMLの`input`で使われている型が使えるのでおすすめです。
```tsx
import type { ComponentPropsWithoutRef } from 'react';
type ToggleProps = Pick<ComponentPropsWithoutRef<'input'>, 'value' | 'onChange'> & {size: (省略)};
```

2022-09-10 13:49 UTC, ituki0426 commented on src/components/Toggle/index.tsx
> +            <input id="toggle" type="checkbox" onClick={onClick} className="peer sr-only" />
```ts
import type { FC } from 'react';
import { useState } from 'react';
import Toggle from '@/components/Toggle';

const ToggleFet: FC = () => {
	const [toggleState,setToggleState]=useState<'day1'|'day2'>('day1');
  return (
    <main className="flex justify-center">
     <span className='mr-1 text-5xl'>day1</span>
	 <Toggle
	 onClick={()=>{
		if(toggleState==='day1'){
			setToggleState('day2')
		}else{
			setToggleState('day1')
		}
	 }}
	  />
	<span className='ml-1 text-5xl'>day2</span>
    </main>
  );
};

export default ToggleFet;

```

上記のように使用することを想定しているのですが直したほうが良いでしょうか？

![image](https://user-images.githubusercontent.com/82156802/189486385-33c00297-bdb2-441d-9e84-92101d163ee2.png)

2022-09-10 22:54 UTC, ReoHakase commented on src/components/Toggle/index.tsx
> +            <input id="toggle" type="checkbox" onClick={onClick} className="peer sr-only" />
まず、`checked`属性を設定することができないと、初期値の設定ができません。例えば、二日目には初期値を`day2`にしておく...ということが実現できなくなります。また、今のコードだと`checked`が`day1 | day2`により制御されていないので、別途クリック以外で`toggleState`の値を変更したときにUIが追随しません。
なので、引数付きの`onChange: (event: React.ChangeEvent<HTMLInputElement>) => void`と一緒に指定できるようにしたほうがいいと思います。

2022-09-12 01:07 UTC, ituki0426 commented on src/components/Toggle/index.tsx
> +            <input id="toggle" type="checkbox" onClick={onClick} className="peer sr-only" />
わかりました

2022-09-12 07:26 UTC, ituki0426 commented on src/components/Toggle/index.tsx
> +            <input id="toggle" type="checkbox" onClick={onClick} className="peer sr-only" />
変更したので確認お願いします

2022-09-12 07:28 UTC, ReoHakase approved these changes

2022-09-12 07:30 UTC, ReoHakase commented
確認しました✨

2022-09-12 08:00 UTC, merged