`<UserNavigationMenu>`を作成した。
3I-shikosai32/shikosai32-front pull request #71
Opened 2022-09-10 10:53 UTC by ReoHakase

あとでちゃんとかきます

2022-09-10 11:32 UTC, dino3616 approved these changes

2022-09-10 11:35 UTC, dino3616 requested changes

2022-09-10 11:35 UTC, dino3616 commented on src/layouts/components/UserNavigationMenu/index.tsx
> +            <>
ここ`<div>`でお願いします。

2022-09-10 11:43 UTC, ReoHakase commented on src/layouts/components/UserNavigationMenu/index.tsx
> +            <>
`<div>`にすると、見た目を揃えるために`flex flex-col items-start gap-4`みたいなクラスを与えなければならなくなっちゃうけれど、それって冗長じゃないかな...？
フラグメント`<>`ってパフォーマンス悪かったりするんでしょうか。

2022-09-10 11:52 UTC, ReoHakase commented
意見を聞かせてください↓
操作可能なリンクだと示すために、内部で使っている`<Link>`のデフォルトスタイルを太字に設定しています。なので、現状そのスタイルを受け継いでこのメニューのリンクも太字になっているのですが,
Figmaにならってより細めのフォント`weight`にしたほうがいいと思いますか？

2022-09-10 12:03 UTC, dino3616 commented
weight細目が自分は好みです。
今のスタイルだと少しキツキツな印象を受けるので。

2022-09-10 12:07 UTC, dino3616 commented on src/layouts/components/UserNavigationMenu/index.tsx
> +            <>
自分は[これ](https://zenn.dev/januswel/articles/c80ac055b72955d71d41)を信じ切っていますが...実際のところどれくらいの積み重なりでどれくらいの影響が出るのかは分からないです。
ちなみに自分は筆者と同じくチリツモは怖い派です。
ただ冗長という意見もすごくよく分かります。
ので、†無責任†ですがここの判断はお任せします。
記事を見た上で決めてください。

2022-09-10 23:15 UTC, ReoHakase commented
> weight細めが自分は好みです。 今のスタイルだと少しキツキツな印象を受けるので。

通常の太さに変更しました。ご確認ください。

2022-09-10 23:19 UTC, ReoHakase commented on src/layouts/components/UserNavigationMenu/index.tsx
> +            <>
このコンポーネントに限った話をすれば、`Array.prototype.map(obj => <>いろいろたくさん</>)`みたいに未知多数のフラグメントを使っているわけではなく、`props`による出し分けで3箇所程度の使用なので、パフォーマンスに有意差はでない...と私は思います。
なので、スタイル記述の簡潔さを優先してフラグメント`<>`を継続使用する方向でいきたいです。よろしいでしょうか？

2022-09-11 02:40 UTC, dino3616 commented on src/layouts/components/UserNavigationMenu/index.tsx
> +            <>
おｋです👍

2022-09-11 02:42 UTC, dino3616 approved these changes

2022-09-11 02:42 UTC, merged