Web Share APIを使った、代替機能を含むシェアボタン`<ShareButton>`を作成した。
3I-shikosai32/shikosai32-front pull request #80
Opened 2022-09-12 07:03 UTC by ReoHakase

- close #79 

# 概要
> OZ at 3Iで現実のボードゲームとスマホを組み合わせたオンラインゲームを楽しもう！

現在開いているページのURLを上記のメッセージとともに共有できる、ネイティブの共有メニューを呼び出すボタン`<ShareButton>`を作成した。
## Windows11での動作例
![image](https://user-images.githubusercontent.com/16751535/189592451-daae52e7-7d52-4c22-85da-9fe141666eb5.png)

## Web Share APIが利用不可なときに代替モーダル
![image](https://user-images.githubusercontent.com/16751535/189592519-db94f9f9-0a7a-45b5-b5b5-c3c23ecb0ed6.png)

# ストーリー
![image](https://user-images.githubusercontent.com/16751535/189592576-6cbdac4e-6a08-43b3-a463-c1487afb1eef.png)

2022-09-12 07:42 UTC, ReoHakase commented
![image](https://user-images.githubusercontent.com/16751535/189599247-fc9e6efd-eb2b-4b4a-86e7-aa44f2b51afa.jpeg)
![image](https://user-images.githubusercontent.com/16751535/189598937-109b45e8-2a42-418a-9aca-b306276f47c3.png)
iOS16 Betaでの動作確認

2022-09-12 09:55 UTC, dino3616 reviewed
共有時のメッセージですが、こんな感じのテキストでどうですか？

<~10/21>
レクリエーションとインターネットの超融合！？
3Iによる出し物「OZ」はマルチメディア教室で展開予定！茨香祭当日をお楽しみに！

<10/22, 10/23>
レクリエーションとインターネットの超融合！？
3Iによる出し物「OZ」がマルチメディア教室で展開中です！

<10/24~>
3Iによる出し物「OZ」で遊んでくれてありがとう！また会う日まで！

2022-09-12 10:16 UTC, ReoHakase commented
> 共有時のメッセージですが、こんな感じのテキストでどうですか？
> 
> 
> 
> <~10/21>
> 
> レクリエーションとインターネットの超融合！？
> 
> 3Iによる出し物「OZ」はマルチメディア教室で展開予定！茨香祭当日をお楽しみに！
> 
> 
> 
> <10/22, 10/23>
> 
> レクリエーションとインターネットの超融合！？
> 
> 3Iによる出し物「OZ」がマルチメディア教室で展開中です！
> 
> 
> 
> <10/24~>
> 
> 3Iによる出し物「OZ」で遊んでくれてありがとう！また会う日まで！

そのアイデアいいですね！！
その場合、共有時の添付テキストとOGPのテキストの両方に使うってことで大丈夫ですかね？

2022-09-12 10:42 UTC, dino3616 commented
OGPのテキストというと？

2022-09-12 10:51 UTC, ReoHakase commented
> OGPのテキストというと？

[引用](https://ogp.me/)

> [Optional Metadata](https://ogp.me/#optional)
The following properties are optional for any object and are generally recommended:

> og:audio - A URL to an audio file to accompany this object.
**og:description** - **A one to two sentence description of your object.**
og:determiner - The word that appears before this object's title in a sentence. An [enum](https://ogp.me/#enum) of (a, an, the, "", auto). If auto is chosen, the consumer of your data should chose between "a" or "an". Default is "" (blank).
og:locale - The locale these tags are marked up in. Of the format language_TERRITORY. Default is en_US.
og:locale:alternate - An [array](https://ogp.me/#array) of other locales this page is available in.
og:site_name - If your object is part of a larger web site, the name which should be displayed for the overall site. e.g., "IMDb".
og:video - A URL to a video file that complements this object.

まず、OGPっていうのは、LINEとかTwitterでURLを貼ると自動で表示される情報を指定できる規格。
そこでサイトの説明文を`og:description`で追加できるんだけれど、これにも日付によってかわるメッセージを設定するのかどうしようかな？っていうのを考えたかった
![image](https://user-images.githubusercontent.com/16751535/189635686-7923dd37-c689-43e5-8ecd-a85e4fca04f0.png)

2022-09-12 12:26 UTC, dino3616 commented
あーこの説明文meta descriptionだと思ってた。
`og:description`はmeta descriptionと同じでいいんじゃない...？
あまり

2022-09-12 12:28 UTC, ReoHakase commented
それで問題なさそう

2022-09-13 02:59 UTC, ReoHakase commented
`<meta>`タグでの説明文記載は、サイト共通のメタデータ用コンポーネント`<CommonMeta>`を作る際に別のPRで実装するので、問題ないようでしたらApproveお願いします！

2022-09-14 09:19 UTC, dino3616 requested changes

2022-09-14 09:19 UTC, dino3616 commented on src/layouts/components/ShareButton/resolveShareMessage.ts
> +  if (isAfter(date, DAY2)) {
またPendingのままリクチェン送るの忘れてました(愚か

2022-09-14 11:46 UTC, dino3616 approved these changes

2022-09-14 11:46 UTC, merged