カスタムフック`useUserNavigationMenu`を作成した。
3I-shikosai32/shikosai32-front pull request #83
Opened 2022-09-13 02:02 UTC by ReoHakase

2022-09-14 11:45 UTC, dino3616 requested changes

2022-09-14 11:45 UTC, dino3616 commented on src/layouts/components/UserNavigationMenu/hooks/useUserNavigationMenu.ts
> +    loggedIn: !!data.findUser?.id,
`boolean`型なので`isLoggedIn`の方がいいかもしれない。

2022-09-14 11:45 UTC, dino3616 commented on src/libs/graphql/documents/query/FindUserBio.gql
> +    id
Bioに関するフィールドは`UserBioParts`みたいなfragmentにまとめちゃった方が再利用しやすいですね。

2022-09-14 11:45 UTC, dino3616 commented on src/libs/graphql/handlers/query/FindUserBio.ts
> +  const [userBio] = useFindUserBioQuery({ variables: { id: uid || '' }, pause: !uid });
今回`character`と`iconUrl`は可変になる(予定)なので、request policyは`cache-and-network`を指定しましょう。

2022-09-23 19:40 UTC, ReoHakase commented on src/libs/graphql/documents/query/FindUserBio.gql
> +    id
フラグメントから切り出し、その後、そのGraphQLのフラグメント`UserBio`の名前を`UserBioData`に修正しました。
ご確認ください✔️

2022-09-23 19:52 UTC, dino3616 commented on src/libs/graphql/documents/query/FindUserBio.gql
> +    id
👍

2022-09-23 19:52 UTC, dino3616 approved these changes

2022-09-23 19:53 UTC, merged